### PR TITLE
bugfix: fix invalid bit range when assign ipv6 address

### PR DESCRIPTION
**Pull request by houstar**
Signed-off-by: Leno Hou <lenohou@gmail.com>

### CODE REVIEW

**Comment by allencloud** [comment]
Could you please add more description that why why should fix this? @houstar 
Thanks a lot.

In addition, the upstream is also has the `>=`, should we fix the upstream?

**Comment by houstar** [comment]
When assign IPv6 address,  the IPv6 address will be reached to the mask (as h.bits) here, so it occurred invalid bit range. 

@allencloud  Yes, we should push this to upstream since upstream not yet fixed this issue.

**Comment by rudyfly** [comment]
LGTM

**Comment by rudyfly** [comment]
@houstar Please update our vendor in pouch-container, thank you.

**Pull request merged**
